package com.spym.LiveView.service

enum class MainServiceActions {
    START_SERVICE,SETUP_VIEWS,END_CALL,SWITCH_CAMERA,TOGGLE_AUDIO,TOGGLE_VIDEO,TOGGLE_AUDIO_DEVICE,SEND_SWITCH_CAMERA,
    TOGGLE_SCREEN_SHARE,STOP_SERVICE
}